// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeXc5xLwvc2QGYmgk-x6_kRGxnc8Oe_c',
    appId: '1:42704641356:web:d22d5df0b41b4478ba03e9',
    messagingSenderId: '42704641356',
    projectId: 'mentormenteeconnect2',
    authDomain: 'mentormenteeconnect2.firebaseapp.com',
    storageBucket: 'mentormenteeconnect2.firebasestorage.app',
    measurementId: 'G-6LTST8TETN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDLW5v3cVD5RXnLG213sOBiv6OQdIe38',
    appId: '1:42704641356:android:7cc2df9371522d39ba03e9',
    messagingSenderId: '42704641356',
    projectId: 'mentormenteeconnect2',
    storageBucket: 'mentormenteeconnect2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCECkOD1I56Y-7IMNubqyfRp6vicP9DhZg',
    appId: '1:42704641356:ios:0eefba25985e9f21ba03e9',
    messagingSenderId: '42704641356',
    projectId: 'mentormenteeconnect2',
    storageBucket: 'mentormenteeconnect2.firebasestorage.app',
    iosBundleId: 'com.example.mentorMate',
  );

}