// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCviJoznPmTzrSJ1cG3JM7JBDJqWGJw3vQ',
    appId: '1:502974249840:web:9be87f12c6049747a6edb5',
    messagingSenderId: '502974249840',
    projectId: 'mentormate-ce439',
    authDomain: 'mentormate-ce439.firebaseapp.com',
    storageBucket: 'mentormate-ce439.firebasestorage.app',
    measurementId: 'G-HT0VCFRVVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluAXUtxbdxPl7uq0brWncQ08IFxv93SY',
    appId: '1:502974249840:android:e7bf836fbd139c9fa6edb5',
    messagingSenderId: '502974249840',
    projectId: 'mentormate-ce439',
    storageBucket: 'mentormate-ce439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXwgPpIX56FuBwbexEV-0Dm0HxK4EwezY',
    appId: '1:502974249840:ios:053593e3ee339d26a6edb5',
    messagingSenderId: '502974249840',
    projectId: 'mentormate-ce439',
    storageBucket: 'mentormate-ce439.firebasestorage.app',
    iosBundleId: 'com.example.mentorMate',
  );
}
